### PR TITLE
fix milking cooldown popup

### PR DESCRIPTION
**Pull request by simonLeary42**
introduced in https://github.com/Chakyl/society-sunlit-valley/commit/3b437bc021bd806ca1da3205d2c9a0d051ab76c9

```
entities/animalBase.js#281: Error occurred while handling scheduled event callback: TypeError: Cannot find function getSanitizedETALangArg in object {petGifts=[{animal: buzzier_bees:grizzly_bear, gifts: [society:beemonican_seal]}, {animal: minecraft:wolf, gifts: [simplehats:longfoxears, betterarcheology:wolf_fossil]}, {animal: minecraft:cat, gifts: [simplehats:nekoears, betterarcheology:ocelot_fossil]}, {animal: quark:foxhound, ...
```

## Pull Request name
fix milking cooldown popup

## PR checklist
Check all that apply
- [x] I have read the [contribution guide](https://github.com/Chakyl/society-sunlit-valley?tab=readme-ov-file#contribution-guide)
- [x] Bugfix, typos, documentation
- [ ] New content
- [ ] Changes to existing content
- [ ] Translation
- [ ] Work in this PR contains AI generated text, images, or code

## Changelog
- fix milking cooldown popup

### CODE REVIEW

**Comment by simonLeary42** [comment]
This didn't work, I am still not getting any popups.

**Comment by Chakyl** [comment]
I would avoid trying to fix bugs on the active dev branch, the reason they aren't popping up is because they require the latest ver of embers text api, but you can't load that version in the pack unless you have a mod update of sunlit tweaks I have locally that is unreleased
